In [ ]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import confusion_matrix, classification_report

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [ ]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
df = pd.read_csv("lending_data.csv")
# Review the DataFrame
df.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [ ]:
# Separate the data into labels and features
# Separate the y variable, the labels
y = df["loan_status"]
# Separate the X variable, the features
X = df[[col for col in df.columns if col != "loan_status"]]

In [ ]:
# Review the y variable Series
y.head()

0    0
1    0
2    0
3    0
4    0
Name: loan_status, dtype: int64

In [ ]:
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 77536 entries, 0 to 77535
Series name: loan_status
Non-Null Count  Dtype
--------------  -----
77536 non-null  int64
dtypes: int64(1)
memory usage: 605.9 KB


In [ ]:
# Review the X variable DataFrame
X.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  
0                 1       22800  
1                 0       13600  
2                 0       16100  
3                 1       22700  
4                 1       23000

### Step 3: Split the data into training and testing datasets by using `train_test_split`.

In [ ]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=1)

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [ ]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
model = LogisticRegression(solver = 'lbfgs', max_iter = 100, random_state = 1)
# Fit the model using training data
model = model.fit(X_train,y_train)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [ ]:
# Make a prediction using the testing data
predictions = model.predict(X_test)

### Step 3: Evaluate the model’s performance by doing the following:

* Generate a confusion matrix.

* Print the classification report.

In [ ]:
# Generate a confusion matrix for the model
matrix = confusion_matrix(y_test, predictions)
print(matrix)

[[18663   102]
 [   56   563]]


In [ ]:
# Print the classification report for the model
report = classification_report(y_test, predictions)
print(report)

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.85      0.91      0.88       619

    accuracy                           0.99     19384
   macro avg       0.92      0.95      0.94     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The model demonstrates exceptional performance in predicting healthy loans (0), achieving a precision of 100% and a recall of 99%. While the prediction of high-risk loans (1) also shows acceptable precision and accuracy, the precision rate is slightly lower due to a significant number of false positives generated by the model.

---

**Test of Random Forest Model**

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
model2 = RandomForestRegressor()

model2 = model2.fit(X_train,y_train)

In [ ]:
predictions = model2.predict(X_test)

In [ ]:
if y_test.dtype != predictions.dtype:
    if y_test.dtype == np.int64:
        predictions = predictions.astype(np.int64)
    else:
        y_test = y_test.astype(np.int64)

In [ ]:
matrix2 = confusion_matrix(y_test,predictions)
print(matrix2)

[[18720    45]
 [  356   263]]


In [ ]:
report2 = classification_report(y_test,predictions)
print(report2)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99     18765
           1       0.85      0.42      0.57       619

    accuracy                           0.98     19384
   macro avg       0.92      0.71      0.78     19384
weighted avg       0.98      0.98      0.98     19384



-----------------------------------------

**Test of Gradient Boosting Regressor model**

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

In [ ]:
model3 = GradientBoostingRegressor()

In [ ]:
model3 = model3.fit(X_train,y_train)

In [ ]:
predictions = model3.predict(X_test)

In [ ]:
threshold = 0.5
predictions[predictions >= threshold] = 1
predictions[predictions < threshold] = 0

In [ ]:
matrix3 = confusion_matrix(y_test,predictions)
print(matrix3)

[[18652   113]
 [    7   612]]


In [ ]:
report3 = classification_report(y_test,predictions)
print(report3)

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.84      0.99      0.91       619

    accuracy                           0.99     19384
   macro avg       0.92      0.99      0.95     19384
weighted avg       0.99      0.99      0.99     19384

